version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    networks:
      - backend
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./app/config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    env_file:
      - ./app/config/.env

  app:
    build: app
    ports:
      - 3200:3200
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge