version: "3.8"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./app/config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "8097:8097"
    depends_on:
      database:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
